# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

# [sncast.default]                                         # Define a profile name
# url = "https://free-rpc.nethermind.io/sepolia-juno/v0_7" # Url of the RPC provider
# accounts-file = "../account-file"                        # Path to the file with the account data
# account = "mainuser"                                     # Account from `accounts_file` or default account file that will be used for the transactions
# keystore = "~/keystore"                                  # Path to the keystore file
# wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
# block-explorer = "StarkScan"                             # Block explorer service used to display links to transaction details
# show-explorer-links = true                               # Print links pointing to pages with transaction details in the chosen block explorer

[sncast.default]
url = "https://starknet-sepolia.public.blastapi.io"       # RPC de Sepolia testnet
accounts-file = "/home/alebeta/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "braavos"                                       # Usar cuenta de Braavos
wait-params = { timeout = 300, retry-interval = 10 }      # Parámetros de espera
block-explorer = "StarkScan"                              # Explorador de bloques
show-explorer-links = true                                # Mostrar enlaces al explorador

# Configuración para Sepolia testnet con Braavos
[sncast.sepolia]
url = "https://starknet-sepolia.public.blastapi.io"
accounts-file = "/home/alebeta/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "braavos"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "StarkScan"
show-explorer-links = true

# Perfil específico para declarar contratos
[sncast.declare]
url = "https://starknet-sepolia.public.blastapi.io"
accounts-file = "/home/alebeta/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "braavos"
wait-params = { timeout = 600, retry-interval = 15 }
block-explorer = "StarkScan"
show-explorer-links = true